#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Config-Std
Version  : 0.903
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/B/BR/BRICKER/Config-Std-0.903.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BR/BRICKER/Config-Std-0.903.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libc/libconfig-std-perl/libconfig-std-perl_0.903-1.debian.tar.xz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-Config-Std-license
Requires: perl-Config-Std-man
BuildRequires : perl(Class::Std)

%description
Config::Std version 0.903
This module implements yet another damn configuration-file system.

%package license
Summary: license components for the perl-Config-Std package.
Group: Default

%description license
license components for the perl-Config-Std package.


%package man
Summary: man components for the perl-Config-Std package.
Group: Default

%description man
man components for the perl-Config-Std package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Config-Std-0.903
mkdir -p %{_topdir}/BUILD/Config-Std-0.903/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Config-Std-0.903/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Config-Std
cp LICENSE %{buildroot}/usr/share/doc/perl-Config-Std/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Config/Std.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Config-Std/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Config::Std.3
